"""Build a single self-contained HTML report (open it in any browser, print to PDF)."""
from __future__ import annotations

import html
from datetime import datetime

import pandas as pd

from core import eda
from core.profile import describe_step
from core.theme import style

CSS = """
body{font-family:'IBM Plex Sans',-apple-system,Segoe UI,Roboto,sans-serif;color:#1F2933;background:#FBFAF7;max-width:1000px;margin:32px auto;padding:0 20px;line-height:1.55}
h1,h2{font-family:'Source Serif 4',Georgia,serif}h1{font-size:30px;margin-bottom:0}h2{margin-top:36px;border-bottom:1px solid #DAD6CE;padding-bottom:6px;font-size:20px}
.sub{color:#5F6B76;margin-top:4px}.kpis{display:flex;flex-wrap:wrap;gap:12px;margin:16px 0}
.kpi{flex:1;min-width:140px;border:1px solid #DAD6CE;border-radius:4px;padding:14px 16px;background:#fff}
.kpi b{display:block;font-size:24px;color:#1E5A78}.kpi span{font-size:12px;color:#5F6B76;text-transform:uppercase;letter-spacing:.04em}
table{border-collapse:collapse;width:100%;font-size:13px;margin:10px 0}th,td{border-bottom:1px solid #DAD6CE;padding:6px 10px;text-align:left}
th{background:#F3F1EB}.warn{background:#FFFBEB;border-left:3px solid #B7791F;padding:8px 12px;margin:6px 0;border-radius:0 4px 4px 0}
li{margin:4px 0}.foot{color:#5F6B76;font-size:12px;margin-top:40px}@media print{.chart{break-inside:avoid}}
"""


def _table(df: pd.DataFrame, max_rows: int = 30) -> str:
    return df.head(max_rows).to_html(index=False, border=0, na_rep="", float_format=lambda v: f"{v:,.3f}".rstrip("0").rstrip("."))


def build_html(df: pd.DataFrame, raw: pd.DataFrame, steps: list[dict], prof_before: dict, prof_after: dict,
               name: str, extra_figs: list | None = None, model_summary: list[str] | None = None) -> str:
    esc = html.escape
    b, a = prof_before["overview"], prof_after["overview"]
    insights = eda.generate_insights(df)
    warnings = eda.guardrails(df)
    figs = []
    heat = eda.correlation_heatmap(df)
    if heat is not None:
        figs.append(heat)
    for c in eda.numeric_cols(df)[:3]:
        figs.append(eda.chart_for(df, c))
    figs += list(extra_figs or [])
    first = True
    chart_html = []
    for f in figs:
        if f is None:
            continue
        chart_html.append(f"<div class='chart'>{style(f, 380).to_html(full_html=False, include_plotlyjs='cdn' if first else False)}</div>")
        first = False

    kpi = lambda label, value: f"<div class='kpi'><b>{esc(str(value))}</b><span>{esc(label)}</span></div>"
    parts = [f"<!doctype html><html><head><meta charset='utf-8'><title>Data report: {esc(name)}</title><style>{CSS}</style></head><body>",
             f"<h1>Data analysis report</h1><p class='sub'>{esc(name)} &middot; generated {datetime.now():%d %b %Y, %H:%M}</p>",
             "<h2>Overview</h2><div class='kpis'>",
             kpi("Quality score (before)", f"{b['quality_score']}/100"), kpi("Quality score (after)", f"{a['quality_score']}/100"),
             kpi("Rows", f"{a['rows']:,}"), kpi("Columns", a["columns"]), kpi("Missing cells (after)", f"{a['missing_cells']:,}"),
             "</div>"]
    parts.append("<h2>Cleaning steps applied</h2>")
    parts.append("<ol>" + "".join(f"<li>{esc(describe_step(s))}</li>" for s in steps) + "</ol>" if steps
                 else "<p>No cleaning steps were applied; this report describes the original data.</p>")
    parts.append("<h2>Key insights</h2><ul>" + "".join(f"<li>{esc(i)}</li>" for i in insights) + "</ul>"
                 if insights else "<h2>Key insights</h2><p>No notable patterns found.</p>")
    if warnings:
        parts.append("<h2>Cautions</h2>" + "".join(f"<div class='warn'>{esc(w)}</div>" for w in warnings))
    if model_summary:
        parts.append("<h2>Predictive model</h2><ul>" + "".join(f"<li>{esc(m).replace('**', '')}</li>" for m in model_summary) + "</ul>")
    num = eda.summary_numeric(df)
    if not num.empty:
        parts.append("<h2>Numeric summary</h2>" + _table(num.reset_index().rename(columns={"index": "column"})))
    cat = eda.summary_categorical(df)
    if not cat.empty:
        parts.append("<h2>Categorical summary</h2>" + _table(cat))
    if chart_html:
        parts.append("<h2>Charts</h2>" + "".join(chart_html))
    parts.append("<h2>Data preview</h2>" + _table(df, 15))
    parts.append("<p class='foot'>Generated by the Intelligent Data Analytics Platform. Every figure above can be reproduced "
                 "by replaying the saved pipeline on the original file.</p></body></html>")
    return "".join(parts)
